# Generated by Django 4.0.5 on 2022-09-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_users',
        ),
    ]
