# Generated by Django 4.0.5 on 2022-09-11 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PAuthQQUser',
            new_name='OAuthQQUser',
        ),
    ]
