# Generated by Django 4.0.5 on 2022-08-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='odi',
            new_name='oid',
        ),
    ]
