# Generated by Django 4.0.5 on 2022-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodsvisitcount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsvisitcount',
            name='count',
            field=models.IntegerField(default=0, verbose_name='访问量'),
        ),
    ]
